dependencies:
  - pip:
      - semantic-link==0.7.6
      - azure-ai-textanalytics==5.3.0b2
      - opencensus-ext-azure==1.1.9
      - typing-extensions==4.11.0
      - pydicom==2.4.3
      - pydantic==2.4.0
      - httpx==0.27.2
      - openai==1.42.0
      - Pillow==10.0.0